name: Fetch Lotto Data

on:
    schedule:
      - cron: '0 14 * * *'  # 2:00 PM UTC = 10:00 PM SGT
    workflow_dispatch:
  
jobs:
  fetch-lotto-data:
    runs-on: ubuntu-latest

    steps:
      - name: Fetch Lotto Data
        run: |
          TODAY=$(date +'%Y%m%d')
          curl -s -X GET "https://lotto-insight.vercel.app/api/scrape?dateRange=${TODAY}-"