name: 4D Data Fetch

on:
  schedule:
    - cron: '*/5 * * * *'  # Every 5 minutes
  workflow_dispatch:

jobs:
  call-scrape-api:
    runs-on: ubuntu-latest

    steps:
      - name: Call scrape API with today's date
        run: |
          TODAY=$(date +'%Y%m%d')
          curl -s -X GET "https://lotto-insight.vercel.app/api/scrape?dateRange=${TODAY}-"